# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrn.xdc

# Block Designs: bd/bdesign_clock_core/bdesign_clock_core.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core || ORIG_REF_NAME==bdesign_clock_core} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_clk_wiz_0_0/bdesign_clock_core_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_clk_wiz_0_0 || ORIG_REF_NAME==bdesign_clock_core_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_microblaze_riscv_0_0/bdesign_clock_core_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_microblaze_riscv_0_0 || ORIG_REF_NAME==bdesign_clock_core_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_dlmb_v10_0/bdesign_clock_core_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_dlmb_v10_0 || ORIG_REF_NAME==bdesign_clock_core_dlmb_v10_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_ilmb_v10_0/bdesign_clock_core_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_ilmb_v10_0 || ORIG_REF_NAME==bdesign_clock_core_ilmb_v10_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_dlmb_bram_if_cntlr_0/bdesign_clock_core_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bdesign_clock_core_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_ilmb_bram_if_cntlr_0/bdesign_clock_core_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bdesign_clock_core_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_lmb_bram_0/bdesign_clock_core_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_lmb_bram_0 || ORIG_REF_NAME==bdesign_clock_core_lmb_bram_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_mdm_1_0/bdesign_clock_core_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_mdm_1_0 || ORIG_REF_NAME==bdesign_clock_core_mdm_1_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_rst_clk_wiz_0_100M_0/bdesign_clock_core_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==bdesign_clock_core_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bdesign_clock_core_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_axi_smc_0 || ORIG_REF_NAME==bdesign_clock_core_axi_smc_0} -quiet] -quiet

# Block Designs: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/bd_128c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_1/bd_128c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_2/bd_128c_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_3/bd_128c_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_4/bd_128c_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_5/bd_128c_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_6/bd_128c_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_7/bd_128c_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_8/bd_128c_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_9/bd_128c_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_10/bd_128c_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_11/bd_128c_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_12/bd_128c_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_13/bd_128c_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_14/bd_128c_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_15/bd_128c_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_16/bd_128c_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_17/bd_128c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_18/bd_128c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_19/bd_128c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_20/bd_128c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_21/bd_128c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_22/bd_128c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_23/bd_128c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_24/bd_128c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_25/bd_128c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_26/bd_128c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_27/bd_128c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_28/bd_128c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_29/bd_128c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_30/bd_128c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_31/bd_128c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_32/bd_128c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_33/bd_128c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_34/bd_128c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_35/bd_128c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_36/bd_128c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_37/bd_128c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_38/bd_128c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_39/bd_128c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_axi_uartlite_0_0/bdesign_clock_core_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_axi_uartlite_0_0 || ORIG_REF_NAME==bdesign_clock_core_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bdesign_clock_core/ip/bdesign_clock_core_i2s_dds_0_0/bdesign_clock_core_i2s_dds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bdesign_clock_core_i2s_dds_0_0 || ORIG_REF_NAME==bdesign_clock_core_i2s_dds_0_0} -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_clk_wiz_0_0/bdesign_clock_core_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_clk_wiz_0_0 || ORIG_REF_NAME==bdesign_clock_core_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_clk_wiz_0_0/bdesign_clock_core_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_clk_wiz_0_0 || ORIG_REF_NAME==bdesign_clock_core_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_clk_wiz_0_0/bdesign_clock_core_clk_wiz_0_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_microblaze_riscv_0_0/bdesign_clock_core_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_microblaze_riscv_0_0 || ORIG_REF_NAME==bdesign_clock_core_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_microblaze_riscv_0_0/bdesign_clock_core_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_lmb_bram_0/bdesign_clock_core_lmb_bram_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_mdm_1_0/bdesign_clock_core_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_mdm_1_0 || ORIG_REF_NAME==bdesign_clock_core_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_mdm_1_0/bdesign_clock_core_mdm_1_0_ooc_trace.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_rst_clk_wiz_0_100M_0/bdesign_clock_core_rst_clk_wiz_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==bdesign_clock_core_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_1/bd_128c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_2/bd_128c_arinsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_3/bd_128c_rinsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_4/bd_128c_awinsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_5/bd_128c_winsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_6/bd_128c_binsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_7/bd_128c_aroutsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_8/bd_128c_routsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_9/bd_128c_awoutsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_10/bd_128c_woutsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_11/bd_128c_boutsw_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_12/bd_128c_arni_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_13/bd_128c_rni_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_14/bd_128c_awni_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_15/bd_128c_wni_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_16/bd_128c_bni_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_20/bd_128c_s00a2s_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_21/bd_128c_sarn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_22/bd_128c_srn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_23/bd_128c_sawn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_24/bd_128c_swn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_25/bd_128c_sbn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_26/bd_128c_m00s2a_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_27/bd_128c_m00arn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_28/bd_128c_m00rn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_29/bd_128c_m00awn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_30/bd_128c_m00wn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_31/bd_128c_m00bn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_33/bd_128c_m01s2a_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_34/bd_128c_m01arn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_35/bd_128c_m01rn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_36/bd_128c_m01awn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_37/bd_128c_m01wn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/bd_0/ip/ip_38/bd_128c_m01bn_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_axi_smc_0 || ORIG_REF_NAME==bdesign_clock_core_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_uartlite_0_0/bdesign_clock_core_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bdesign_clock_core_axi_uartlite_0_0 || ORIG_REF_NAME==bdesign_clock_core_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/ip/bdesign_clock_core_axi_uartlite_0_0/bdesign_clock_core_axi_uartlite_0_0_ooc.xdc

# XDC: c:/tesi2s/nobufgmux_dds/nobufgmux.gen/sources_1/bd/bdesign_clock_core/bdesign_clock_core_ooc.xdc
